(add-to-list 'load-path "~/.emacs.d/configs")

(require 'rs-packages)
(require 'rs-editor)
(require 'rs-themes)
(require 'rs-powerline)
(require 'rs-functions)
(require 'rs-env)
(require 'rs-key-bindings)

(require 'rs-editing)
(require 'rs-ido)
(require 'rs-company)
(require 'rs-shell)
(require 'rs-irc)
(require 'rs-org)
(require 'rs-clojure)
(require 'rs-markdown)
(require 'rs-javascript)
(require 'rs-csharp)
(require 'rs-neotree)
(require 'rs-snippets)
(require 'rs-git)
(require 'rs-server)
