(add-to-list 'load-path "~/.emacs.d/configs")

(load "~/.emacs.d/configs/rs-packages")
(load "~/.emacs.d/configs/rs-editor")
(load "~/.emacs.d/configs/rs-themes")
(load "~/.emacs.d/configs/rs-powerline")
(load "~/.emacs.d/configs/rs-functions")

(load "~/.emacs.d/configs/rs-editing")
(load "~/.emacs.d/configs/rs-ido")
(load "~/.emacs.d/configs/rs-shell")
(load "~/.emacs.d/configs/rs-irc")
(load "~/.emacs.d/configs/rs-clojure")
(load "~/.emacs.d/configs/rs-markdown")
(load "~/.emacs.d/configs/rs-javascript")
(load "~/.emacs.d/configs/rs-csharp")
